#!/bin/bash

# Extended glob pattern: !(*.ejs)
shopt -s extglob
# When no file matches glob, don't treat the pattern as literal string
shopt -s nullglob

commit_hash=`git rev-parse --short HEAD`

for dir in ./src/notetypes/*/ ; do
    NOTETYPE_DIR="./Note Types/$(basename "${dir}")"

    for file in "${NOTETYPE_DIR}"/* ; do
        rm "$file"
    done

    front_file="${NOTETYPE_DIR}/Front Template.html"
    back_file="${NOTETYPE_DIR}/Back Template.html"

    # Use node script to render EJS with views set to project root
    node -e "
      const ejs = require('ejs');
      const fs = require('fs');
      const path = require('path');

      const rootDir = process.cwd();
      const frontPath = path.join(rootDir, '${dir}front.ejs');
      const backPath = path.join(rootDir, '${dir}back.ejs');

      const frontHtml = ejs.render(fs.readFileSync(frontPath, 'utf8'), {}, {
        filename: frontPath,
        views: [rootDir]
      });
      const backHtml = ejs.render(fs.readFileSync(backPath, 'utf8'), {}, {
        filename: backPath,
        views: [rootDir]
      });

      fs.writeFileSync('${front_file}', frontHtml);
      fs.writeFileSync('${back_file}', backHtml);
    "

    echo "<!-- version ${commit_hash} -->" | cat - "${front_file}" > /tmp/out && mv /tmp/out "${front_file}"
    echo "<!-- version ${commit_hash} -->" | cat - "${back_file}" > /tmp/out && mv /tmp/out "${back_file}"

    for file in "${dir}"!(*.ejs) ; do
        cp "$file" "${NOTETYPE_DIR}/$(basename "$file")"
    done
done
